package HallBooking;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chiranth
 */
public class ManageBookingsForm extends javax.swing.JFrame {

    /**
     * Creates new form ManagerBookingsForm
     */
    
    BOOKING booking = new BOOKING();
    
    public ManageBookingsForm() {
        initComponents();
        
        booking.fillBookingJTable(jTable1);
        
        jTable1.setRowHeight(25);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButtonaddBooking = new javax.swing.JToggleButton();
        jToggleButtoneditBooking = new javax.swing.JToggleButton();
        jToggleButtonremoveBooking = new javax.swing.JToggleButton();
        jToggleButtonclearfields = new javax.swing.JToggleButton();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldCustomerID = new javax.swing.JTextField();
        jTextFieldHallNO = new javax.swing.JTextField();
        jToggleRefresh = new javax.swing.JToggleButton();
        jDateChooserDateIN = new com.toedter.calendar.JDateChooser();
        jDateChooserDateOUT = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage Bookings");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(0.0F);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer ID:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date In:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date Out:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hall Number:");

        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer ID", "Hall Number", "Date In", "Date Out"
            }
        )
        //make jtable cells not editable
        {
            public boolean isCellEditable(int row, int column)
            {return false;}
        }
    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jToggleButtonaddBooking.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonaddBooking.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonaddBooking.setText("Add New Booking");
    jToggleButtonaddBooking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jToggleButtonaddBooking.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonaddBookingActionPerformed(evt);
        }
    });

    jToggleButtoneditBooking.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtoneditBooking.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtoneditBooking.setText("Edit");
    jToggleButtoneditBooking.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtoneditBookingActionPerformed(evt);
        }
    });

    jToggleButtonremoveBooking.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonremoveBooking.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonremoveBooking.setText("Remove");
    jToggleButtonremoveBooking.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonremoveBookingActionPerformed(evt);
        }
    });

    jToggleButtonclearfields.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonclearfields.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonclearfields.setText("Clear");
    jToggleButtonclearfields.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonclearfieldsActionPerformed(evt);
        }
    });

    jTextFieldID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldIDActionPerformed(evt);
        }
    });

    jTextFieldCustomerID.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

    jTextFieldHallNO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldHallNO.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldHallNOActionPerformed(evt);
        }
    });

    jToggleRefresh.setBackground(new java.awt.Color(204, 204, 204));
    jToggleRefresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleRefresh.setText("Refresh");
    jToggleRefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleRefreshActionPerformed(evt);
        }
    });

    jDateChooserDateIN.setDateFormatString("dd-MM-yyyy");

    jDateChooserDateOUT.setDateFormatString("dd-MM-yyyy");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel2)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldHallNO, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jDateChooserDateOUT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserDateIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addGap(42, 47, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButtonclearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButtonaddBooking)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtoneditBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonremoveBooking)
                    .addGap(18, 18, 18)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jToggleRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldHallNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jDateChooserDateIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jDateChooserDateOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButtonaddBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtoneditBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtonremoveBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addComponent(jToggleButtonclearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jToggleRefresh)
                    .addGap(0, 46, Short.MAX_VALUE))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        // display selected row
        // get jtabel model
        DefaultTableModel model= (DefaultTableModel)jTable1.getModel();

        // get selectde row index
        int rIndex = jTable1.getSelectedRow();

        // display data
        jTextFieldID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldCustomerID.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldHallNO.setText(model.getValueAt(rIndex, 2).toString());
        
        //display date
        try {
            Date dateIn = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rIndex, 3).toString());
            jDateChooserDateIN.setDate(dateIn);
            Date dateOut = (Date) new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rIndex, 4).toString());
            jDateChooserDateOUT.setDate(dateOut);
        } catch (ParseException ex) {
            Logger.getLogger(ManageBookingsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleButtonaddBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonaddBookingActionPerformed

        try{
            
            int customer_id = Integer.valueOf(jTextFieldCustomerID.getText());
            int hall_number = Integer.valueOf(jTextFieldHallNO.getText());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String date_in = dateFormat.format(jDateChooserDateIN.getDate());
            String date_out = dateFormat.format(jDateChooserDateOUT.getDate());
            String toDayDate = dateFormat.format(new Date());
            
            Date din = dateFormat.parse(date_in);
            Date dout = dateFormat.parse(date_out);
            Date tdd = dateFormat.parse(toDayDate);
            
            //if the date_in is before or not equal to today date
            if(!(din.after(tdd) || din.equals(tdd)))
            {
                JOptionPane.showMessageDialog(rootPane, "DateIn must be after or equal to today","DateIn Error", JOptionPane.ERROR_MESSAGE);
            }
            
            //if the date_out is before date_in or not equal to date_in
            else if(!(dout.after(din) || dout.equals(din))){
                JOptionPane.showMessageDialog(rootPane, "DateOut must be after or equal to DateIn","DateOut Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(booking.addBooking(customer_id, hall_number, date_in , date_out))
                {
                JOptionPane.showMessageDialog(rootPane, "New Booking Added Successfully","Add Booking", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                JOptionPane.showMessageDialog(rootPane, "Booking Not Added","Add Booking Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
        }
        catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Room Number","Input Field Error", JOptionPane.WARNING_MESSAGE);
            }
        catch(ParseException ex){
            Logger.getLogger(ManageBookingsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jToggleButtonaddBookingActionPerformed

    private void jToggleButtoneditBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtoneditBookingActionPerformed
        
        // edit the selected Booking;
        
            try
            {   
                int bookingid = Integer.parseInt(jTextFieldID.getText());
                int hallnumber = Integer.parseInt(jTextFieldHallNO.getText());
                int customerid = Integer.parseInt(jTextFieldCustomerID.getText());
                
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String date_in = dateFormat.format(jDateChooserDateIN.getDate());
                String date_out = dateFormat.format(jDateChooserDateOUT.getDate());
                
                String toDayDate = dateFormat.format(new Date());
            
                Date din = dateFormat.parse(date_in);
                Date dout = dateFormat.parse(date_out);
                Date tdd = dateFormat.parse(toDayDate);
                
                //if the date_in is before or not equal to today date
                if(!(din.after(tdd) || din.equals(tdd)))
                {
                    JOptionPane.showMessageDialog(rootPane, "Date In must be after or equal to today","DateIn Error", JOptionPane.ERROR_MESSAGE);
                }
            
                //if the date_out is before date_in or not equal to date_in
                else if(!(dout.after(din) || dout.equals(din))){
                    JOptionPane.showMessageDialog(rootPane, "Date Out must be after or equal to Date In","Date Out Error", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    if(booking.editBooking(bookingid, customerid, hallnumber, date_in, date_out))
                    {
                    JOptionPane.showMessageDialog(rootPane, "Booking Data Updated Successfully","Edit Booking", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else
                    {
                    JOptionPane.showMessageDialog(rootPane, "Booking Data Not Updated","Edit Booking error", JOptionPane.ERROR_MESSAGE);
                    }
                  }
            }
                
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Booking ID + Customer ID","Booking ID Error", JOptionPane.WARNING_MESSAGE);
            }
            catch(NullPointerException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ " Select the Date IN & OUT","Booking ID Error", JOptionPane.WARNING_MESSAGE);
            }
            catch(ParseException ex)
            {
            Logger.getLogger(ManageBookingsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
    }//GEN-LAST:event_jToggleButtoneditBookingActionPerformed

    private void jToggleButtonremoveBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonremoveBookingActionPerformed
        
        // Delete Hall
        try
            {
                int bookingid = Integer.valueOf(jTextFieldID.getText());
                
                if(booking.removeBooking(bookingid))
                {
                    JOptionPane.showMessageDialog(rootPane, "Booking Deleted Successfully","Remove Booking", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Booking Not Deleted","Remove Booking error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Booking Number","Booking ID Error", JOptionPane.WARNING_MESSAGE);
            }
        
    }//GEN-LAST:event_jToggleButtonremoveBookingActionPerformed

    private void jToggleButtonclearfieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonclearfieldsActionPerformed
        
    // remove text form all jTextfields
        jTextFieldCustomerID.setText("");
        jTextFieldID.setText("");
        jTextFieldHallNO.setText("");
        
        jDateChooserDateIN.setDate(null);
        jDateChooserDateOUT.setDate(null);
        
    }//GEN-LAST:event_jToggleButtonclearfieldsActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldHallNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHallNOActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextFieldHallNOActionPerformed

    private void jToggleRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRefreshActionPerformed
        //clear the jtable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Booking ID","Customer ID", "Hall Number", "Date In", "Date Out"}));

        // populate the jtable
        booking.fillBookingJTable(jTable1);
    }//GEN-LAST:event_jToggleRefreshActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBookingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBookingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBookingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBookingsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManageBookingsForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooserDateIN;
    private com.toedter.calendar.JDateChooser jDateChooserDateOUT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCustomerID;
    private javax.swing.JTextField jTextFieldHallNO;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JToggleButton jToggleButtonaddBooking;
    private javax.swing.JToggleButton jToggleButtonclearfields;
    private javax.swing.JToggleButton jToggleButtoneditBooking;
    private javax.swing.JToggleButton jToggleButtonremoveBooking;
    private javax.swing.JToggleButton jToggleRefresh;
    // End of variables declaration//GEN-END:variables
}
