package HallBooking;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chiranth
 */
public class ManageCustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form ManagerCustomerform
     */
    
    CUSTOMER customer = new CUSTOMER();
    
    public ManageCustomerForm() {
        initComponents();
        
        // add a white border to the clear fields button
        
        //Border border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        //jToggleButtonclearfields.setBorder(border);
        
        //populate the jtable
        customer.fillcustomerJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButtonaddcustomer = new javax.swing.JToggleButton();
        jToggleButtoneditcustomer = new javax.swing.JToggleButton();
        jToggleButtonremovecustomer = new javax.swing.JToggleButton();
        jToggleButtonclearfields = new javax.swing.JToggleButton();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldFname = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldphone = new javax.swing.JTextField();
        jTextFieldLname = new javax.swing.JTextField();
        jToggleRefresh = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage Customer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(0.0F);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone No:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phone", "Email"
            }
        )
        //make jtable cells not editable
        {
            public boolean isCellEditable(int row, int column)
            {return false;}
        }
    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jToggleButtonaddcustomer.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonaddcustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonaddcustomer.setText("Add New Customer");
    jToggleButtonaddcustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jToggleButtonaddcustomer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonaddcustomerActionPerformed(evt);
        }
    });

    jToggleButtoneditcustomer.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtoneditcustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtoneditcustomer.setText("Edit");
    jToggleButtoneditcustomer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtoneditcustomerActionPerformed(evt);
        }
    });

    jToggleButtonremovecustomer.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonremovecustomer.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonremovecustomer.setText("Remove");
    jToggleButtonremovecustomer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonremovecustomerActionPerformed(evt);
        }
    });

    jToggleButtonclearfields.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonclearfields.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonclearfields.setText("Clear");
    jToggleButtonclearfields.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonclearfieldsActionPerformed(evt);
        }
    });

    jTextFieldid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldidActionPerformed(evt);
        }
    });

    jTextFieldFname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

    jTextFieldemail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldemailActionPerformed(evt);
        }
    });

    jTextFieldphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldphone.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldphoneActionPerformed(evt);
        }
    });

    jTextFieldLname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldLnameActionPerformed(evt);
        }
    });

    jToggleRefresh.setBackground(new java.awt.Color(204, 204, 204));
    jToggleRefresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleRefresh.setText("Refresh");
    jToggleRefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleRefreshActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))))
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(42, 42, 42))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButtonclearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButtonaddcustomer)
                            .addGap(18, 18, 18)
                            .addComponent(jToggleButtoneditcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                    .addComponent(jToggleButtonremovecustomer)
                    .addGap(18, 18, 18)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(jToggleRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(50, 50, 50))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButtonaddcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtoneditcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtonremovecustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addComponent(jToggleButtonclearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jToggleRefresh)
                    .addGap(0, 21, Short.MAX_VALUE))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtoneditcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtoneditcustomerActionPerformed
        // edit the selected clint;
        
        int id = 0;
        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldphone.getText();
        String email = jTextFieldemail.getText();
        
        if(fname.trim().equals("") || lname.trim().equals("")|| phone.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields --> First & Last name & Phone number","Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            try
            {
                id = Integer.valueOf(jTextFieldid.getText());
                
                if(customer.editCustomer(id, fname, lname, phone, email))
                {
                    JOptionPane.showMessageDialog(rootPane, "Customer Data Updated Successfully","Edit Customer", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Customer Data Not Updated","Edit Customer error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Customer ID {Number}","Customer ID Error", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        
        //clear the jtable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","First Name","Last Name","Phone","Email"}));
        
        // populate the jtable
        customer.fillcustomerJTable(jTable1);
        
    }//GEN-LAST:event_jToggleButtoneditcustomerActionPerformed

    private void jToggleButtonremovecustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonremovecustomerActionPerformed
        // Delete customer
        try
            {
                int id = Integer.valueOf(jTextFieldid.getText());
                
                if(customer.removeCustomer(id))
                {
                    JOptionPane.showMessageDialog(rootPane, "Customer Deleted Successfully","Remove Customer", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Customer Not Deleted","Remove Customer error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Customer ID {Number}","Customer ID Error", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_jToggleButtonremovecustomerActionPerformed

    private void jToggleButtonclearfieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonclearfieldsActionPerformed
        // remove text form all jTextfields
        jTextFieldid.setText("");
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        jTextFieldphone.setText("");
        jTextFieldemail.setText("");
        
    }//GEN-LAST:event_jToggleButtonclearfieldsActionPerformed

    private void jTextFieldphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldphoneActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    private void jToggleButtonaddcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonaddcustomerActionPerformed
        
        // add new clint
        
        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldphone.getText();
        String email = jTextFieldemail.getText();
        
        if(fname.trim().equals("") || lname.trim().equals("")|| phone.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields --> First & Last name & Phone number","Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            if(customer.addCustomer(fname, lname, phone, email))
            {
            JOptionPane.showMessageDialog(rootPane, "New Customer Added Successfully","Add Customer", JOptionPane.INFORMATION_MESSAGE);
            }else{
            JOptionPane.showMessageDialog(rootPane, "Customer Not Added","Add Customer error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jToggleButtonaddcustomerActionPerformed

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // display selected row
        // get jtabel model
        DefaultTableModel model= (DefaultTableModel)jTable1.getModel();

        // get selectde row index
        int rIndex = jTable1.getSelectedRow();

        // display data
        jTextFieldid.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldFname.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldLname.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldphone.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldemail.setText(model.getValueAt(rIndex, 4).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRefreshActionPerformed
        //clear the jtable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","First Name","Last Name","Phone","Email"}));
        
        // populate the jtable
        customer.fillcustomerJTable(jTable1);
    }//GEN-LAST:event_jToggleRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageCustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageCustomerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldphone;
    private javax.swing.JToggleButton jToggleButtonaddcustomer;
    private javax.swing.JToggleButton jToggleButtonclearfields;
    private javax.swing.JToggleButton jToggleButtoneditcustomer;
    private javax.swing.JToggleButton jToggleButtonremovecustomer;
    private javax.swing.JToggleButton jToggleRefresh;
    // End of variables declaration//GEN-END:variables
}
