package HallBooking;

import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chiranth
 */
public class ManageHallForm extends javax.swing.JFrame {

    /**
     * Creates new form ManagerHallForm
     */
    
    HALLS hall = new HALLS();
    
    public ManageHallForm() {
        initComponents();
        
        //Display room Type ID in combobox
        hall.fillHall_TypeJCombobox(jComboBoxType);
        
        //show all rooms in JTable
        hall.fillHallsJTable(jTable1);
        
        //Set height to the jTable
        jTable1.setRowHeight(40);
        
        //create a buuton group for radiobutton
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonYES);
        bg.add(jRadioButtonNO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToggleButtonaddHall = new javax.swing.JToggleButton();
        jToggleButtoneditHall = new javax.swing.JToggleButton();
        jToggleButtonremoveHall = new javax.swing.JToggleButton();
        jToggleButtonclearfields = new javax.swing.JToggleButton();
        jTextFieldNumber = new javax.swing.JTextField();
        jTextFieldphone = new javax.swing.JTextField();
        jToggleRefresh = new javax.swing.JToggleButton();
        jComboBoxType = new javax.swing.JComboBox<>();
        jButtonShowTypes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonYES = new javax.swing.JRadioButton();
        jRadioButtonNO = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1002, 544));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1002, 550));

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Manage Halls");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(424, 424, 424))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hall Number:");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(0.0F);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hall Type:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone No:");

        jTable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number","Type","Phone","Booking"
            }
        )
        //make jtable cells not editable
        {
            public boolean isCellEditable(int row, int column)
            {return false;}
        }
    );
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jToggleButtonaddHall.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonaddHall.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonaddHall.setText("Add New Hall");
    jToggleButtonaddHall.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jToggleButtonaddHall.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonaddHallActionPerformed(evt);
        }
    });

    jToggleButtoneditHall.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtoneditHall.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtoneditHall.setText("Edit");
    jToggleButtoneditHall.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtoneditHallActionPerformed(evt);
        }
    });

    jToggleButtonremoveHall.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonremoveHall.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonremoveHall.setText("Remove");
    jToggleButtonremoveHall.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonremoveHallActionPerformed(evt);
        }
    });

    jToggleButtonclearfields.setBackground(new java.awt.Color(204, 204, 204));
    jToggleButtonclearfields.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleButtonclearfields.setText("Clear");
    jToggleButtonclearfields.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleButtonclearfieldsActionPerformed(evt);
        }
    });

    jTextFieldNumber.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldNumber.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldNumberActionPerformed(evt);
        }
    });

    jTextFieldphone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jTextFieldphone.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextFieldphoneActionPerformed(evt);
        }
    });

    jToggleRefresh.setBackground(new java.awt.Color(204, 204, 204));
    jToggleRefresh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jToggleRefresh.setText("Refresh");
    jToggleRefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jToggleRefreshActionPerformed(evt);
        }
    });

    jComboBoxType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jComboBoxType.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBoxTypeActionPerformed(evt);
        }
    });

    jButtonShowTypes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
    jButtonShowTypes.setText("Show types");
    jButtonShowTypes.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonShowTypesActionPerformed(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Booking:");

    jPanel3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    jRadioButtonYES.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jRadioButtonYES.setText("YES");
    jRadioButtonYES.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButtonYESActionPerformed(evt);
        }
    });

    jRadioButtonNO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    jRadioButtonNO.setText("NO");
    jRadioButtonNO.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jRadioButtonNOActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jRadioButtonYES)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jRadioButtonNO)
            .addContainerGap(18, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButtonYES)
                .addComponent(jRadioButtonNO))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleButtonaddHall)
                            .addGap(41, 41, 41)
                            .addComponent(jToggleButtoneditHall, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jToggleButtonclearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(8, 8, 8)
                    .addComponent(jToggleButtonremoveHall))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldphone)
                        .addComponent(jTextFieldNumber)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonShowTypes)
                            .addGap(14, 14, 14))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1)
                    .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                    .addComponent(jToggleRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(58, 58, 58))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonShowTypes))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButtonaddHall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtoneditHall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButtonremoveHall, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGap(18, 30, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jToggleButtonclearfields, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jToggleRefresh))
            .addGap(47, 47, 47))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    
        // display selected row
        // get jtabel model
        DefaultTableModel model= (DefaultTableModel)jTable1.getModel();

        // get selectde row index
        int rIndex = jTable1.getSelectedRow();

        // display data
        jTextFieldNumber.setText(model.getValueAt(rIndex, 0).toString());
        jComboBoxType.setSelectedItem(model.getValueAt(rIndex, 1));
        jTextFieldphone.setText(model.getValueAt(rIndex, 2).toString());
        
        String isBooked = model.getValueAt(rIndex, 3).toString();
        
        if(isBooked.equals("YES"))
        {
            jRadioButtonYES.setSelected(true);
        }
        else if(isBooked.equals("NO"))
        {
            jRadioButtonNO.setSelected(true);
        }

        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleButtoneditHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtoneditHallActionPerformed
        
        // edit the selected Halls;
        
        int hallnumber = 0;
        int type = Integer.valueOf(jComboBoxType.getSelectedItem().toString());
        String phone = jTextFieldphone.getText();
        String isBooked = "NO";
        
        if(jRadioButtonYES.isSelected())
        {
            isBooked = "YES";
        }
        
        if(phone.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Enter the HALL Phone number","Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            try
            {
                hallnumber = Integer.valueOf(jTextFieldNumber.getText());
                
                if(hall.editHall(hallnumber, type, phone, isBooked))
                {
                    JOptionPane.showMessageDialog(rootPane, "Hall Data Updated Successfully","Edit Hall", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Hall Data Not Updated","Edit Hall error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Hall ID {Number}","Hall ID Error", JOptionPane.WARNING_MESSAGE);
            }
            
        }
        
        
    }//GEN-LAST:event_jToggleButtoneditHallActionPerformed

    private void jToggleButtonremoveHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonremoveHallActionPerformed
        // Delete Hall
        try
            {
                int hallnumber = Integer.valueOf(jTextFieldNumber.getText());
                
                if(hall.removeHall(hallnumber))
                {
                    JOptionPane.showMessageDialog(rootPane, "Hall Deleted Successfully","Remove Hall", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Hall Not Deleted","Remove Hall error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Hall Number","Hall ID Error", JOptionPane.WARNING_MESSAGE);
            }        
    }//GEN-LAST:event_jToggleButtonremoveHallActionPerformed

    private void jToggleButtonclearfieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonclearfieldsActionPerformed
        
        // remove text form all jTextfields
        jTextFieldNumber.setText("");
        jTextFieldphone.setText("");
        jComboBoxType.setSelectedIndex(0);
        jRadioButtonYES.setSelected(false);
        jRadioButtonNO.setSelected(false);
        

    }//GEN-LAST:event_jToggleButtonclearfieldsActionPerformed

    private void jTextFieldNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumberActionPerformed

    private void jTextFieldphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldphoneActionPerformed

    private void jToggleRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRefreshActionPerformed
        //clear the jtable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Number","Type","Phone","Booking"}));

        // populate the jtable
        hall.fillHallsJTable(jTable1);
    }//GEN-LAST:event_jToggleRefreshActionPerformed

    private void jComboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypeActionPerformed

    private void jToggleButtonaddHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonaddHallActionPerformed
        
        try{
            
            int HallNumber = Integer.valueOf(jTextFieldNumber.getText());
            int HallType = Integer.valueOf(jComboBoxType.getSelectedItem().toString());
            String phone = jTextFieldphone.getText();
            
            if(hall.addHall(HallNumber, HallType, phone))
            {
                JOptionPane.showMessageDialog(rootPane, "New Hall Added Successfully","Add Hall", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Hall Not Added","Add Hall Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(NumberFormatException ex)
            {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage()+ "Enter the Room Number","Room ID Error", JOptionPane.WARNING_MESSAGE);
            }
        
    }//GEN-LAST:event_jToggleButtonaddHallActionPerformed

    private void jRadioButtonYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonYESActionPerformed

    private void jRadioButtonNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNOActionPerformed

    private void jButtonShowTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowTypesActionPerformed
        
        HallTypesForm TypesForm = new HallTypesForm();
        TypesForm.setVisible(true);
        TypesForm.pack();
        TypesForm.setLocationRelativeTo(null);
        TypesForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButtonShowTypesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageHallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageHallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageHallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageHallForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageHallForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShowTypes;
    private javax.swing.JComboBox<String> jComboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonNO;
    private javax.swing.JRadioButton jRadioButtonYES;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNumber;
    private javax.swing.JTextField jTextFieldphone;
    private javax.swing.JToggleButton jToggleButtonaddHall;
    private javax.swing.JToggleButton jToggleButtonclearfields;
    private javax.swing.JToggleButton jToggleButtoneditHall;
    private javax.swing.JToggleButton jToggleButtonremoveHall;
    private javax.swing.JToggleButton jToggleRefresh;
    // End of variables declaration//GEN-END:variables
}
